# Set up the prompt
autoload -U colors && colors
setopt PROMPT_SUBST
PROMPT='%{$fg[yellow]%}$(basename $(pwd)) %{$fg_bold[green]%(1j $fg_no_bold[green] )%}—%{$fg_bold[green]%(?  $fg_no_bold[red])%}—%{$reset_color%} '
case $TERM in
  screen*)
    precmd() {
      printf "\033k$(pwd)\033\\"
    }
    preexec() {
      printf "\033k$(echo "$1" | cut -d" " -f1)\033\\"
    }
esac

# GLORIOUS VIM
#bindkey -v

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
setopt histignorealldups sharehistory
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Set up some aliases.
alias ls="ls --color=auto --classify"
alias l='ls -lFh'     # size,show type,human readable
alias la='ls -lAFh'   # long list,show almost all,show type,human readable
alias lr='ls -tRFh'   # sorted by date,recursive,show type,human readable
alias lt='ls -ltFh'   # long list,sorted by date,show type,human readable
alias ll='ls -l'      # long list

alias unexport='unset'
alias whereami=display_info

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias xcopy='xclip -i -selection clipboard'
alias xpaste='xclip -o -selection clipboard'

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval `dircolors "$HOME/dotfiles/dircolors-solarized/dircolors.ansi-dark"`
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Setup zsh-autosuggestions
source "$HOME/dotfiles/zsh/zsh-autosuggestions/autosuggestions.zsh"

AUTOSUGGESTION_HIGHLIGHT_COLOR="fg=10"
AUTOSUGGESTION_ACCEPT_RIGHT_ARROW=1

# Enable autosuggestions automatically
zle-line-init() {
    zle autosuggest-start
}

zle -N zle-line-init

# use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# zsh-autosuggestions is designed to be unobtrusive)
bindkey '^T' autosuggest-toggle

